- hosts: security_group_jenkins_security_group_webserver_dmz
  become: true
  tasks:
  
  - name: Remove previous code
    file:
      path: /var/www/html/website
      state: absent

  - git:
      repo: https://github.com/giridharuniverse21/giripress.git
      dest: /var/www/html/website
